---

# Runtime
verbose: 7
secret:
  token: "lstbknd"

host: "hub.lstbknd.net"
issuer: "registry.lstbknd.net"
service: "hub.lstbknd.net"
key: "/opt/cert/hub/server/hub.lstbknd.net.key.pem"

# Database and Messages broker
psql: "host=127.0.0.1 port=5432 user=lastbackend password=lastbackend dbname=registry sslmode=disable binary_parameters=yes"

api:
  host: 0.0.0.0
  port: 2955
  tls:
    insecure: false
    ca: "/opt/cert/registry/ca.pem"
    cert: "/opt/cert/registry/server.pem"
    key: "/opt/cert/registry/server-key.pem"
  blob_storage:
    type: "s3"
    access_id: ""
    secret_key: ""
    region: ""
    bucket_name: ""
    root_dir: "/lastbackend/registry"
    ssl: true

builder:
  tls:
    insecure: false
    ca: "/opt/cert/builder/ca.pem"
    cert: "/opt/cert/builder/client.pem"
    key: "/opt/cert/builder/client-key.pem"